# Generated by Django 5.2.1 on 2025-08-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('public', 'Public with Code'), ('private', 'Invitation Only')], default='public', max_length=10)),
                ('allow_upload', models.BooleanField(default=True)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_tag', models.BooleanField(default=False)),
                ('allow_comment', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('theme_color', models.CharField(choices=[('emerald', 'Emerald'), ('gold', 'Gold'), ('purple', 'Purple'), ('blue', 'Blue'), ('coral', 'Coral')], default='emerald', max_length=20)),
                ('event_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
